// TTLC — TotalEnergies Marketing CI (énergie). SYSCOHADA, FCFA bruts.
// Source : données MADIS (income + balance + cash existants en base). Correction découverts.
// ⚠️ 2024 bilan MADIS suspect (PNC=66 Mds sur total 191 Mds — ratio >34%) → null pour sous-totaux 2024.
// ⚠️ 2025 income+cash MADIS OK, balance vide (pas de breakdown CP/PNC/PC disponible).
export default {
  ebe: {},

  income: [
    {
      periode: '2022',
      revenu_total: 584623000000,
      cout_ventes: null,
      resultat_exploitation: 16509000000,
      charges_financieres_nettes: null,
      resultat_avant_impots: null,
      impots: null,
      resultat_net: 12279000000,
      actions_en_circulation: null,
      benefice_par_action: null,
      dividende_par_action: 0,
    },
    {
      periode: '2023',
      revenu_total: 589577000000,
      cout_ventes: null,
      resultat_exploitation: 12087000000,
      charges_financieres_nettes: null,
      resultat_avant_impots: null,
      impots: null,
      resultat_net: 8709000000,
      actions_en_circulation: null,
      benefice_par_action: null,
      dividende_par_action: 0,
    },
    {
      periode: '2024',
      revenu_total: 630948000000,
      cout_ventes: null,
      resultat_exploitation: 10491000000,
      charges_financieres_nettes: null,
      resultat_avant_impots: null,
      impots: null,
      resultat_net: 9374000000,
      actions_en_circulation: null,
      benefice_par_action: null,
      dividende_par_action: 0,
    },
    {
      periode: '2025',
      revenu_total: 597865000000,
      cout_ventes: null,
      resultat_exploitation: 12329000000,
      charges_financieres_nettes: null,
      resultat_avant_impots: null,
      impots: null,
      resultat_net: 9087000000,
      actions_en_circulation: null,
      benefice_par_action: null,
      dividende_par_action: 0,
    },
  ],

  balance: [
    {
      periode: '2022',
      total_actifs: 159651000000,
      total_actif_non_courant: null,
      actifs_incorporels: null,
      immobilisations_nettes: null,
      investissements_long_terme: null,
      total_actif_circulant: null,
      stocks: null,
      creances_clients: null,
      tresorerie_equivalents: null,
      total_passif: 159651000000,
      total_capitaux_propres: 49270000000,
      capital_social: null,
      reserves_benefices_non_repartis: null,
      passif_non_courant: 4820000000,
      dette_long_terme: null,
      passif_courant: 105561000000, // 93 336 + 12 225 (DCT = découverts inclus)
      dette_court_terme: 12225000000,
      fournisseurs: null,
      autres_passifs_courants: null,
    },
    {
      periode: '2023',
      total_actifs: 167625000000,
      total_actif_non_courant: null,
      actifs_incorporels: null,
      immobilisations_nettes: null,
      investissements_long_terme: null,
      total_actif_circulant: null,
      stocks: null,
      creances_clients: null,
      tresorerie_equivalents: null,
      total_passif: 167625000000,
      total_capitaux_propres: 45699000000,
      capital_social: null,
      reserves_benefices_non_repartis: null,
      passif_non_courant: 2435000000,
      dette_long_terme: null,
      passif_courant: 119491000000, // 103 635 + 15 856
      dette_court_terme: 15856000000,
      fournisseurs: null,
      autres_passifs_courants: null,
    },
    {
      // 2024 : PNC MADIS suspect (66 Mds sur total 191 Mds) → sous-totaux nulls
      periode: '2024',
      total_actifs: 191526000000,
      total_actif_non_courant: null,
      actifs_incorporels: null,
      immobilisations_nettes: null,
      investissements_long_terme: null,
      total_actif_circulant: null,
      stocks: null,
      creances_clients: null,
      tresorerie_equivalents: null,
      total_passif: 191526000000,
      total_capitaux_propres: null,
      capital_social: null,
      reserves_benefices_non_repartis: null,
      passif_non_courant: null,
      dette_long_terme: null,
      passif_courant: null,
      dette_court_terme: null,
      fournisseurs: null,
      autres_passifs_courants: null,
    },
    {
      periode: '2025',
      total_actifs: 188472000000,
      total_actif_non_courant: null,
      actifs_incorporels: null,
      immobilisations_nettes: null,
      investissements_long_terme: null,
      total_actif_circulant: null,
      stocks: null,
      creances_clients: null,
      tresorerie_equivalents: null,
      total_passif: 188472000000,
      total_capitaux_propres: null,
      capital_social: null,
      reserves_benefices_non_repartis: null,
      passif_non_courant: null,
      dette_long_terme: null,
      passif_courant: null,
      dette_court_terme: null,
      fournisseurs: null,
      autres_passifs_courants: null,
    },
  ],

  cash: [
    {
      periode: '2022',
      flux_exploitation: 14817000000,
      resultat_net: 12279000000,
      depreciation_amortissement: null,
      variation_bfr: null,
      flux_investissement: -9935000000,
      investissements_ppe: null,
      flux_financement: -14830000000,
      remboursement_dette: null,
      dividendes_verses: null,
      variation_tresorerie: null,
      tresorerie_debut_periode: null,
      tresorerie_fin_periode: null,
    },
    {
      periode: '2023',
      flux_exploitation: 20501000000,
      resultat_net: 8709000000,
      depreciation_amortissement: null,
      variation_bfr: null,
      flux_investissement: -8914000000,
      investissements_ppe: null,
      flux_financement: -14814000000,
      remboursement_dette: null,
      dividendes_verses: null,
      variation_tresorerie: null,
      tresorerie_debut_periode: null,
      tresorerie_fin_periode: null,
    },
    {
      periode: '2024',
      flux_exploitation: 27909000000,
      resultat_net: 9374000000,
      depreciation_amortissement: null,
      variation_bfr: null,
      flux_investissement: -11754000000,
      investissements_ppe: null,
      flux_financement: -13330000000,
      remboursement_dette: null,
      dividendes_verses: null,
      variation_tresorerie: null,
      tresorerie_debut_periode: null,
      tresorerie_fin_periode: null,
    },
    {
      periode: '2025',
      flux_exploitation: 10196000000,
      resultat_net: 9087000000,
      depreciation_amortissement: null,
      variation_bfr: null,
      flux_investissement: -10124000000,
      investissements_ppe: null,
      flux_financement: -13793000000,
      remboursement_dette: null,
      dividendes_verses: null,
      variation_tresorerie: null,
      tresorerie_debut_periode: null,
      tresorerie_fin_periode: null,
    },
  ],
};
