import type { ParsedNotation } from './types.js';

export const MOCK_NOTATIONS: Record<string, ParsedNotation> = {
  SNTS: {
    agence: 'Bloomfield Investment',
    note: 'A+',
    perspective: 'Stable',
    court_terme: 'A1-',
    long_terme: 'A+',
    date_notation: '2024-11-15',
    source_url: 'https://www.richbourse.com/common/notation-financiere/index/SNTS',
    history: [],
  },
  ETIT: {
    agence: 'Bloomfield Investment',
    note: 'A',
    perspective: 'Positive',
    court_terme: 'A2',
    long_terme: 'A',
    date_notation: '2024-09-20',
    source_url: 'https://www.richbourse.com/common/notation-financiere/index/ETIT',
    history: [],
  },
  BOABF: {
    agence: 'GCR Ratings',
    note: 'BBB+',
    perspective: 'Stable',
    court_terme: null,
    long_terme: 'BBB+',
    date_notation: '2024-06-10',
    source_url: 'https://www.richbourse.com/common/notation-financiere/index/BOABF',
    history: [],
  },
  SGBC: {
    agence: 'Bloomfield Investment',
    note: 'BBB',
    perspective: 'Négative',
    court_terme: null,
    long_terme: 'BBB',
    date_notation: '2024-03-01',
    source_url: 'https://www.richbourse.com/common/notation-financiere/index/SGBC',
    history: [],
  },
  SIVC: {
    agence: 'Bloomfield Investment',
    note: 'B+',
    perspective: 'Stable',
    court_terme: null,
    long_terme: 'B+',
    date_notation: '2023-12-15',
    source_url: 'https://www.richbourse.com/common/notation-financiere/index/SIVC',
    history: [],
  },
};
