/** Événements mock pour développer/tester sans dépendre de brvm.org. */
import type { MarketEvent } from './types.js';

export function buildMockEvents(): MarketEvent[] {
  return [
    {
      event_date: '2026-05-14',
      event_datetime: '2026-05-14T09:00:00Z',
      source: 'BRVM',
      source_url: 'https://www.brvm.org/fr/emetteurs/type-annonces/communiques',
      source_type: 'communique',
      title: 'SONATEL — Mise en paiement du dividende 2025',
      summary: 'Le conseil annonce un dividende de 1 750 FCFA par action.',
      event_type: 'dividende',
      issuer_name: 'Sonatel',
      instrument_code: 'SNTS',
      sector: 'Télécommunications',
      country_code: 'SN',
      importance_level: 4,
      sentiment: 'positive',
      tags: ['dividende', 'telecom'],
      related_codes: ['SNTS'],
    },
    {
      event_date: '2026-05-12',
      event_datetime: null,
      source: 'BRVM',
      source_url: 'https://www.brvm.org/fr/marche/avis-et-publications/avis',
      source_type: 'avis',
      title: 'SGBCI — Résultats du 1er trimestre 2026',
      summary: 'Produit net bancaire en hausse de 8% sur un an.',
      event_type: 'resultats',
      issuer_name: 'Société Générale CI',
      instrument_code: 'SGBC',
      sector: 'Finance',
      country_code: 'CI',
      importance_level: 3,
      sentiment: 'positive',
      tags: ['resultats', 'banque'],
      related_codes: ['SGBC'],
    },
    {
      event_date: '2026-05-08',
      event_datetime: null,
      source: 'BRVM',
      source_url: 'https://www.brvm.org/fr/informations-permanentes',
      source_type: 'info_permanente',
      title: 'ETIT — Convocation à l’Assemblée Générale Ordinaire',
      summary: 'AGO prévue le 30 juin 2026.',
      event_type: 'assemblee',
      issuer_name: 'Ecobank Transnational',
      instrument_code: 'ETIT',
      sector: 'Finance',
      country_code: 'TG',
      importance_level: 2,
      sentiment: 'neutral',
      tags: ['assemblee'],
      related_codes: ['ETIT'],
    },
  ];
}
